### ISSUE TITLE
Issue while running app with docker => "throw "Primary or secondary path was not specified"

### ISSUE THREAD

**Issue by Hardikraja** [intrahealth/gofr#104]
I am getting below error while running docker-compose up

    /gofr/gofr-backend/node_modules/ihrissmartrequire/index.js:13
        throw "Primary or secondary path was not specified"
        ^

Steps I followed to run the app with docker

 1. git clone https://github.com/intrahealth/gofr.git
 2. cd instant/docker/
 3. docker-compose up

It is successfully starting other apps but while running gofr it is getting this error. 

Is there any workaround or solution for this ?

**Comment by Hardikraja** [comment]
@ashaban please help on this.

**Comment by ashaban** [comment]
@Hardikraja kindly try it now, i have pushed a new image

**Comment by Hardikraja** [comment]
@ashaban 
Thank you very much for looking into this issue and making related changes.
Now, after taking new pull of images when I am running docker it is giving below error..

![image](https://github.com/intrahealth/gofr/assets/32297442/15807513-426a-4071-9e35-5adc02d16e69)

Can you please tell me that I have not done any configuration or anything else I am missing to get that run ?

**Comment by ashaban** [comment]
@Hardikraja  I have pushed a new image, kindly pull and let me know if you still have issues.

**Comment by Hardikraja** [comment]
@ashaban Thank you very much. It worked.

Thank you again for your help.
