### ISSUE TITLE
Update and troubleshoot Docker

### ISSUE THREAD

**Issue by citizenrich** [intrahealth/gofr#97]
@ashaban can I have your help with this. I'm updating the Docker images and docker-compose file. I can launch the site, add a DHIS2 data source, do a force sync. But, regardless I can't get back to the home page without an error. Debug attached.

<img width="749" alt="Screenshot 2022-08-27 at 14 04 18" src="https://user-images.githubusercontent.com/2528387/187043041-f066dfac-caab-4bd4-90f0-68c10ba2927e.png">

How to reproduce
```
# start docker, then
git pull
git checkout update-docker
# in one terminal
cd instant/docker/build
docker build --no-cache -t intrahealth/gofr:$(git rev-parse --short HEAD) .
docker tag intrahealth/gofr:$(git rev-parse --short HEAD) intrahealth/gofr
# in another terminal
cd instant/docker/run
docker-compose up
# go to localhost:4000
```

**Comment by ashaban** [comment]
I have pushed a fix for this @citizenrich

**Comment by citizenrich** [comment]
Thanks!
